name: Update Master with Build Artifacts

on:
  push:
    branches:
      - master
jobs:
  update-master:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Build Artifacts
        run: |
          mkdir -p build
          cp -R ../path/to/react/project/build/* build/
        working-directory: ./path/to/build/repo

      - name: Commit and Push Artifacts to Master
        run: |
          git config user.name "vaishakh3627"
          git config user.email "vaishakh3627@gmail.com"
          git add build/*
          git commit -m "Update build artifacts"
          git push origin master
        working-directory: ./path/to/build/repo

