name: Update Master with Build Artifacts

on:
  push:
    branches:
      - master

jobs:
  update-master:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "vaishakh3627"
          git config user.email "vaishakh3627@gmail.com"

      - name: Copy Build Artifacts
        run: |
          mkdir -p build-artifacts
          cp -R ../vaishakh3627/taskmanager/build/build/* 
        working-directory: .

      - name: Commit and Push Artifacts to Master
        run: |
          git add .
          git commit -m "Update build artifacts"
          git push origin master
        working-directory: ./build-artifacts



